/**
* @File Name : EE_CaseRecordFacilityFilter.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : December 17, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | December 17, 2025 |   | Initial Version
**/

public class EE_CaseRecordFacilityFilter {
	@AuraEnabled
	public static void LightningStudio(){
		System.debug('Lightning Studio');
	}
}